#!/usr/bin/env python3
"""
Script to automatically sync references from paper/references.bib to references.bib
based on citations found in main.tex.

Usage:
    python get_refs.py
"""

import re
from pathlib import Path
from typing import Dict, List, Set


def extract_citation_keys_from_tex(tex_file: Path) -> Set[str]:
    """
    Extract all citation keys from a LaTeX file.

    Looks for patterns like \cite{key1, key2, key3} and returns all unique keys.

    Args:
        tex_file: Path to the main.tex file

    Returns:
        Set of citation keys used in the document
    """
    with open(tex_file, 'r', encoding='utf-8') as f:
        content = f.read()

    # Find all \cite{...} commands
    cite_pattern = r'\\cite\{([^}]+)\}'
    matches = re.findall(cite_pattern, content)

    # Extract individual keys (handling comma-separated lists)
    keys = set()
    for match in matches:
        # Split by comma and strip whitespace
        for key in match.split(','):
            keys.add(key.strip())

    return keys


def parse_bib_file(bib_file: Path) -> Dict[str, str]:
    """
    Parse a BibTeX file and return a dictionary mapping citation keys to their entries.

    Args:
        bib_file: Path to the .bib file

    Returns:
        Dictionary mapping citation keys to their full BibTeX entries
    """
    with open(bib_file, 'r', encoding='utf-8') as f:
        content = f.read()

    entries = {}

    # Split on @article, @book, @inproceedings, etc.
    # Pattern matches @type{key, and captures everything until the matching closing brace
    entry_pattern = r'(@\w+\{[^,]+,.*?(?=\n@|\Z))'
    matches = re.findall(entry_pattern, content, re.DOTALL)

    for match in matches:
        # Extract the citation key from the entry
        key_match = re.search(r'@\w+\{([^,]+),', match)
        if key_match:
            key = key_match.group(1).strip()
            # Store the complete entry
            entries[key] = match.strip()

    return entries


def write_bib_file(output_file: Path, entries: List[str]) -> None:
    """
    Write BibTeX entries to a file.

    Args:
        output_file: Path to the output .bib file
        entries: List of BibTeX entry strings to write
    """
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("% Auto-generated references file\n")
        f.write("% Generated by get_refs.py from paper/references.bib\n")
        f.write("% Do not edit manually - run get_refs.py to update\n\n")

        for entry in entries:
            f.write(entry)
            f.write("\n\n")


def main():
    """Main function to sync references."""
    # Define paths
    script_dir = Path(__file__).parent
    tex_file = script_dir / "main.tex"
    paper_bib = script_dir / "paper" / "references.bib"
    output_bib = script_dir / "references.bib"

    # Verify input files exist
    if not tex_file.exists():
        print(f"Error: {tex_file} not found")
        return 1

    if not paper_bib.exists():
        print(f"Error: {paper_bib} not found")
        return 1

    print("Extracting citation keys from main.tex...")
    citation_keys = extract_citation_keys_from_tex(tex_file)
    print(f"Found {len(citation_keys)} unique citation keys:")
    for key in sorted(citation_keys):
        print(f"  - {key}")

    print(f"\nParsing {paper_bib}...")
    paper_entries = parse_bib_file(paper_bib)
    print(f"Found {len(paper_entries)} entries in paper bibliography")

    # Find matching entries
    print("\nMatching citations to entries...")
    matched_entries = []
    missing_keys = []

    for key in sorted(citation_keys):
        if key in paper_entries:
            matched_entries.append(paper_entries[key])
            print(f"  ✓ {key}")
        else:
            missing_keys.append(key)
            print(f"  ✗ {key} (NOT FOUND)")

    if missing_keys:
        print(f"\nWarning: {len(missing_keys)} citation(s) not found in paper/references.bib:")
        for key in missing_keys:
            print(f"  - {key}")
        print("These citations will need to be added manually.")

    # Write output file
    print(f"\nWriting {len(matched_entries)} entries to {output_bib}...")
    write_bib_file(output_bib, matched_entries)

    print(f"\n✓ Successfully created {output_bib}")
    print(f"  - {len(matched_entries)} entries written")
    if missing_keys:
        print(f"  - {len(missing_keys)} entries missing (add manually)")

    return 0


if __name__ == "__main__":
    exit(main())
